# Generated by Django 4.1.2 on 2023-10-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='username',
            field=models.CharField(default='null', max_length=15),
        ),
    ]
