# Generated by Django 4.1.2 on 2023-10-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_product_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='username',
            field=models.CharField(max_length=15),
        ),
    ]
